LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := qing_static
LOCAL_MODULE_FILENAME := qing
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libqing.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../include
include $(PREBUILT_STATIC_LIBRARY)
